### ISSUE TITLE
Visual mode

### ISSUE THREAD

**Issue by medwatt** [evesdropper/dotfiles#1]
Thanks for the guide. I was wondering how could write the snippet below.

```
snippet for "for loop" b
for ${1:item} in ${2:iterable}:
    ${3:${VISUAL:pass}}
endsnippet
```

My attempt is shown below. I was thinking that we could create a function called `get_visual`. In case there's a visual selection, it selection is taken. In case of no visual selection, it takes the sting "pass". How could something like this be written?

```
s( { trig = "for", dscr = "for loop" },
  fmta(
      [[
for <> in <>:
	<>
]]           ,
      { i(1, "item"), i(2, "iterable"), d(3, get_visual("pass")) }
  )
),
```

**Comment by evesdropper** [comment]
Yeah for sure. To do this you want to take advantage of the `user_args` argument of a Dynamic Node function. So we have something like the following:

```lua
local function isempty(s) --util 
  return s == nil or s == ''
end

local get_visual = function(args, parent, _, user_args)
    if isempty(user_args) then
        ret = "silly goofy" -- edit if needed, do something based on empty user_args
    else
        ret = user_args
    end
	if #parent.snippet.env.SELECT_RAW > 0 then
		return sn(nil, i(1, parent.snippet.env.SELECT_RAW))
	else -- If SELECT_RAW is empty, return a blank insert node
        return sn(nil, i(1, ret))
	end
end

-- snippet 
autosnippet({ trig='testvis', name='trig', dscr='dscr'},
    fmt([[
    for <> in <>: 
        <>
    ]],
    { i(1), i(2), d(3, get_visual, {}, {user_args = {"pass"}}) }, -- first table for args, which we don't need but need to put there else passed into args
    { delimiters='<>' }
    )),

```
![dynamic_user_args](https://user-images.githubusercontent.com/82856360/211086197-b924bff2-4dcb-41b9-a5b6-91d42deb6320.gif)

**Comment by medwatt** [comment]
Thanks.

Do happen to have such a snippet already converted to lua?

```
context "math()"
snippet // "Fraction" iA
\\frac{$1}{$2}$0
endsnippet

context "math()"
snippet / "Fraction" i
\\frac{${VISUAL}}{$1}$0
endsnippet

context "math()"
snippet '((\d+)|(\d*)(\\)?([A-Za-z]+)((\^|_)(\{\d+\}|\d))*)/' "symbol frac" wrA
\\frac{`!p snip.rv = match.group(1)`}{$1}$0
endsnippet

priority 1000
context "math()"
snippet '^.*\)/' "() frac" wrA
`!p
stripped = match.string[:-1]
depth = 0
i = len(stripped) - 1
while True:
	if stripped[i] == ')': depth += 1
	if stripped[i] == '(': depth -= 1
	if depth == 0: break;
	i-=1
snip.rv = stripped[0:i] + "\\frac{" + stripped[i+1:-1] + "}"
`{$1}$0
endsnippet
```

**Comment by evesdropper** [comment]
Not at the moment since I haven't had much use for fractions, but will let you know if I add one.

**Comment by medwatt** [comment]
How do you write snippets that use lookbehind in latex?

**Comment by evesdropper** [comment]
Perhaps provide an example? I'm not super familiar with lookbehind regex.

**Comment by medwatt** [comment]
`(?<!\\)(sin|cos|arccot|cot|csc|ln|log|exp|star|perp)`

`?<!` is negative lookbehind. The regex above says match all those inside `()` such as `sin` that are not preceded by `\`.

**Comment by evesdropper** [comment]
Gotcha. In Lua there's no explicit lookbehind, and neither is there support for multiple groups, so finding something that works explicitly the same is quite difficult. I came up with a sort of pattern based on [this stackoverflow post](https://stackoverflow.com/questions/24307006/lua-pattern-similar-to-regex-positive-lookahead) but unfortunately Lua is limited in its patterns.

![image](https://user-images.githubusercontent.com/82856360/211101172-1f21d588-c171-4bbd-a76e-1daa78ae58dc.png)

**Comment by medwatt** [comment]
Thanks for checking it out. I have been playing with luasnip for almost of day now. I'm still on the fence whether I want to jump ships. Writing luasnip snippets is much more tedious than Ultinsips. The lack of proper regex also doesn't help.

**Comment by evesdropper** [comment]
No worries. Personally I switched due to UltiSnips being a bit slower/lagging. LuaSnip also integrates well with nvim-cmp which is also a bonus.

As for snippet writing, it is less intuitive and slower imo but you can gradually create snippets to expedite the process like the ones mentioned in my guide. And as for regex, I'm not sure about the timeline about adding more regex support, but I definitely understand. I've just put some catch all "workarounds" that are a bit clunkier for the moment for stuff involving or expressions or some of the snippets you mentioned (e.g. a postfix that adds `\` to the beginning of the term instead of the lookbehind).

**Comment by medwatt** [comment]
Two more questions if you don't mind.

(1). What sort of snippets do you have that make ultisnips laggy.

(2). Using snippet nodes is quite is nice idea (the ones with `sn`). Looking at some of your snippets, you use `fmt` for the main snippet, yet you revert back to the more tedious definition (the one where the snippet is completely defined with nodes). Why don't use use `fmt` as well inside the `sn` nodes. Isn't the point of using `fmt` in the first place is to improve readability?

**Comment by evesdropper** [comment]
1. not sure exactly what it was if I'm being honest - I just know sometimes UltiSnips would lag a bit and my config was a bit of a mess, so when I rewrote my nvim setup in ~Aug 2022 I tried to use an init.lua and hence decided to switch to LuaSnip
2. I think you can use `fmt` within snippet nodes as well; I just didn't for a few of the initial snippet nodes because they were relatively shorter but I did use `fmta` (similar, but default angle brackets) for my integral snippet [here](https://github.com/L3MON4D3/LuaSnip/wiki/Cool-Snippets#latex---integrals).
